from django.urls import path
from .views import (
    add_flat,
    add_round,
    add_round_tube,
    add_shader,
    add_mag,
    add_vtip,
    delete_flat,
    delete_round,
    delete_round_tube,
    delete_shader,
    delete_mag,
    delete_vtip,
    edit_flat,
    edit_round,
    edit_round_tube,
    edit_shader,
    edit_mag,
    edit_vtip,
    plus_round,
    minus_round,
    shop,
)

urlpatterns = [
    path("shop/", shop, name="shop"),
    path("add_round/", add_round, name="add_round"),
    path("add_shader/", add_shader, name="add_shader"),
    path("add_mag/", add_mag, name="add_mag"),
    path("add_round_tube/", add_round_tube, name="add_round_tube"),
    path("add_vtip/", add_vtip, name="add_vtip"),
    path("add_flat/", add_flat, name="add_flat"),
    path(r"edit_round/<int:id>", edit_round, name="edit_round"),
    path(r"edit_shader/<int:id>", edit_shader, name="edit_shader"),
    path(r"edit_mag/<int:id>", edit_mag, name="edit_mag"),
    path(r"edit_round_tube/<int:id>", edit_round_tube, name="edit_round_tube"),
    path(r"edit_vtip/<int:id>", edit_vtip, name="edit_vtip"),
    path(r"edit_flat/<int:id>", edit_flat, name="edit_flat"),
    path(r"delete_round/<int:pk>", delete_round, name="delete_round"),
    path(r"delete_shader/<int:pk>", delete_shader, name="delete_shader"),
    path(r"delete_mag/<int:pk>", delete_mag, name="delete_mag"),
    path(r"delete_round_tube/<int:pk>", delete_round_tube, name="delete_round_tube"),
    path(r"delete_vtip/<int:pk>", delete_vtip, name="delete_vtip"),
    path(r"delete_flat/<int:pk>", delete_flat, name="delete_flat"),
    path(r"plus_round/<int:id>", plus_round, name="plus_round"),
    path(r"minus_round/<int:id>", minus_round, name="minus_round"),
]
