# Generated by Django 2.2.7 on 2020-01-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='staff_access',
            field=models.BooleanField(default=False),
        ),
    ]
