# Generated by Django 2.2.7 on 2020-01-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='artists')),
                ('about', models.TextField()),
                ('twitter_handle', models.CharField(blank=True, max_length=30)),
                ('instagram_handle', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
