# Generated by Django 2.2.7 on 2019-11-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.IntegerField(max_length=1)),
                ('liner', models.CharField(choices=[('RL', 'Round Liner'), ('TL', 'Tight Liner')], default='RL', max_length=32)),
                ('stock', models.IntegerField(max_length=5)),
            ],
        ),
    ]
