# Generated by Django 2.2.7 on 2020-01-10 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
                ('liner', models.CharField(default='Flat Tube', max_length=32)),
                ('ton', models.CharField(choices=[('Neeedles', 'Needles'), ('Tubes', 'Tubes')], default='Tubes', max_length=20)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
                ('liner', models.CharField(default='Magnum Shader', max_length=32)),
                ('ton', models.CharField(choices=[('Neeedles', 'Needles'), ('Tubes', 'Tubes')], default='Neeedles', max_length=20)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
                ('liner', models.CharField(choices=[('RL', 'Round Liner'), ('TL', 'Tight Liner')], default='RL', max_length=32)),
                ('ton', models.CharField(choices=[('Neeedles', 'Needles'), ('Tubes', 'Tubes')], default='Neeedles', max_length=20)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoundTube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
                ('liner', models.CharField(default='Round Tube', max_length=32)),
                ('ton', models.CharField(choices=[('Neeedles', 'Needles'), ('Tubes', 'Tubes')], default='Tubes', max_length=20)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
                ('liner', models.CharField(default='Round Shader', max_length=32)),
                ('ton', models.CharField(choices=[('Neeedles', 'Needles'), ('Tubes', 'Tubes')], default='Neeedles', max_length=20)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vtip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
                ('liner', models.CharField(default='V Tube', max_length=32)),
                ('ton', models.CharField(choices=[('Neeedles', 'Needles'), ('Tubes', 'Tubes')], default='Tubes', max_length=20)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StockReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('done_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='StockObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('report_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.StockReport')),
            ],
        ),
    ]
