# Generated by Django 2.2.7 on 2019-11-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rounds',
            new_name='Round',
        ),
    ]
