# Generated by Django 2.2.7 on 2019-11-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20191113_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='ton',
            field=models.CharField(choices=[('Neeedles', 'Needles'), ('Tubes', 'Tubes')], default='Neeedles', max_length=20),
        ),
    ]
