# Generated by Django 2.2.7 on 2019-11-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_round_ton'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shaders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
                ('liner', models.CharField(default='Round Shader', max_length=32)),
                ('ton', models.CharField(choices=[('Neeedles', 'Needles'), ('Tubes', 'Tubes')], default='Neeedles', max_length=20)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='round',
            name='size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='round',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
