# Generated by Django 2.2.7 on 2019-11-13 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20191113_1736'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shaders',
            new_name='Shader',
        ),
    ]
