# Generated by Django 2.2.7 on 2019-11-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20191113_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
                ('liner', models.CharField(default='Magnum Shader', max_length=32)),
                ('ton', models.CharField(choices=[('Neeedles', 'Needles'), ('Tubes', 'Tubes')], default='Neeedles', max_length=20)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
