# Generated by Django 2.2.7 on 2019-11-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_stockobject_stockreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockobject',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stockreport',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
